name: build for test

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: build test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      image: ${{ steps.image.outputs.image }}
      sha_short: ${{ steps.image.outputs.sha_short }}

    steps:
      - name: checkout pipeline
        uses: actions/checkout@v4

      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Image URI
        id: image
        run: |
          IMAGE_NAME=ghcr.io/marceloqrz/pokeapi
          SHA_SHORT=${GITHUB_SHA::8}

          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build \
            -f Dockerfile \
            -t ${{ steps.image.outputs.image }}:latest \
            -t ${{ steps.image.outputs.image }}:${{ steps.image.outputs.sha_short }} \
            .

      - name: Push Docker Image to GHCR
        run: |
          docker push ${{ steps.image.outputs.image }}:latest
          docker push ${{ steps.image.outputs.image }}:${{ steps.image.outputs.sha_short }}
  cd:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci

    environment: master

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"serviceId":"<ID_DO_SERVICO>"}' \
            https://api.render.com/v1/services/<ID_DO_SERVICO>/deploys